[project]
name = "ca-masters"
version = "0.1.0"
dependencies = ["numpy", "scipy", "pandas", "matplotlib", "pyyaml", "python-docx"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
